-- Script DDL para la tabla TALLER
CREATE TABLE TALLER (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    SEDE_ID NUMBER NOT NULL,
    EDUCADOR_ID NUMBER NOT NULL,
    TEMA VARCHAR2(255) NOT NULL,
    FECHA_PROGRAMADA TIMESTAMP NOT NULL,
    FECHA_EJECUCION TIMESTAMP,
    ESTADO VARCHAR2(20) DEFAULT 'PLANIFICADO' CHECK (ESTADO IN ('PLANIFICADO', 'EJECUTADO', 'CANCELADO')),
    OBJETIVOS VARCHAR2(1000),
    METODOLOGIA VARCHAR2(1000),
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Script DDL para la tabla PARTICIPANTE_TALLER
CREATE TABLE PARTICIPANTE_TALLER (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    TALLER_ID NUMBER NOT NULL,
    NNA_ID NUMBER NOT NULL,
    ASISTE NUMBER(1) DEFAULT 0 CHECK (ASISTE IN (0, 1)),
    EVALUACION VARCHAR2(500),
    CONSTRAINT FK_PARTICIPANTE_TALLER FOREIGN KEY (TALLER_ID) REFERENCES TALLER(ID) ON DELETE CASCADE
);

-- Índices útiles para las búsquedas comunes
CREATE INDEX IDX_TALLER_SEDE ON TALLER(SEDE_ID);
CREATE INDEX IDX_TALLER_EDUCADOR ON TALLER(EDUCADOR_ID);
CREATE INDEX IDX_PARTICIPANTE_TALLER_ID ON PARTICIPANTE_TALLER(TALLER_ID);
CREATE INDEX IDX_PARTICIPANTE_NNA ON PARTICIPANTE_TALLER(NNA_ID);
