-- 1. DIARIO DE CAMPO
CREATE TABLE DIARIO_CAMPO (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CASO_ID NUMBER NOT NULL,
    FECHA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UBICACION VARCHAR2(500),
    ACTIVIDAD VARCHAR2(1000) NOT NULL,
    ESTADO_FISICO VARCHAR2(100),
    ESTADO_ANIMO VARCHAR2(100),
    OBSERVACIONES VARCHAR2(2000),
    CREADO_POR_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 2. PLAN DE TRABAJO (PTI/PII)
CREATE TABLE PLAN_TRABAJO (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CODIGO_PTI VARCHAR2(50) UNIQUE,
    CASO_ID NUMBER NOT NULL,
    OBJETIVO_GENERAL VARCHAR2(1000),
    FECHA_INICIO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_REVISION TIMESTAMP,
    ESTADO VARCHAR2(50) DEFAULT 'EN_EJECUCION',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE ACCION_PTI (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    PLAN_TRABAJO_ID NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(1000) NOT NULL,
    META VARCHAR2(500),
    PLAZO VARCHAR2(200),
    RESPONSABLE VARCHAR2(200),
    ESTADO VARCHAR2(50) DEFAULT 'PENDIENTE',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ACCION_PTI_PLAN FOREIGN KEY (PLAN_TRABAJO_ID) REFERENCES PLAN_TRABAJO(ID) ON DELETE CASCADE
);

-- 3. DIAGNOSTICO SOCIAL (F04)
CREATE TABLE DIAGNOSTICO_SOCIAL (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CODIGO_FICHA_04 VARCHAR2(50) UNIQUE,
    NNA_ID NUMBER NOT NULL,
    SITUACION_CALLE VARCHAR2(100),
    TIEMPO_EN_CALLE VARCHAR2(100),
    MOTIVO_INGRESO VARCHAR2(500),
    LUGAR_PERNOTA VARCHAR2(500),
    ACTIVIDAD_CALLE VARCHAR2(500),
    CONSUMO_SUSTANCIAS NUMBER(1) DEFAULT 0,
    NOMBRE_TUTOR VARCHAR2(200),
    DNI_TUTOR VARCHAR2(20),
    DIRECCION_TUTOR VARCHAR2(500),
    TELEFONO_TUTOR VARCHAR2(50),
    DATOS_EXTRA CLOB, -- JSON para futuras secciones dinámicas
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 4. SEGUIMIENTO FAMILIAR (F10)
CREATE TABLE SEGUIMIENTO_FAMILIAR (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CASO_ID NUMBER NOT NULL,
    EDUCADOR_ID NUMBER NOT NULL,
    FECHA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TEMA_TRATADO VARCHAR2(500),
    ACUERDOS VARCHAR2(2000),
    EVALUACION VARCHAR2(1000),
    PROXIMA_VISITA TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ÍNDICES
CREATE INDEX IDX_DIARIO_CASO ON DIARIO_CAMPO(CASO_ID);
CREATE INDEX IDX_PLAN_CASO ON PLAN_TRABAJO(CASO_ID);
CREATE INDEX IDX_ACCION_PLAN ON ACCION_PTI(PLAN_TRABAJO_ID);
CREATE INDEX IDX_DIAG_NNA ON DIAGNOSTICO_SOCIAL(NNA_ID);
CREATE INDEX IDX_SEGUIMIENTO_CASO ON SEGUIMIENTO_FAMILIAR(CASO_ID);
