-- Migration 002: Crear tabla NNA_URGENCIA_F15 para Formato 15 (Ficha de Atención Inmediata)
-- Alineado con Diccionario de Datos SEC y Formulario F15.png

CREATE TABLE NNA_URGENCIA_F15 (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CODIGO_REPORTE VARCHAR2(50) UNIQUE NOT NULL, -- URG-YYYY-NNNN
    FECHA_ATENCION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    HORA_ATENCION VARCHAR2(10),
    ZONA_ATENCION VARCHAR2(500),
    NNA_UBICADO NUMBER(1) DEFAULT 0 NOT NULL, -- 0=No, 1=Sí
    PERFIL VARCHAR2(50), -- TRABAJO_CALLE, MENDICIDAD, VIDA_CALLE, OTRO
    ANTECEDENTES VARCHAR2(2000),
    ACTIVIDADES_REALIZA VARCHAR2(2000),
    
    -- Diagnóstico Inmediato
    NOMBRE_REFERIDO VARCHAR2(250),
    DIRECCION_REFERIDA VARCHAR2(500),
    ASISTE_ESCUELA NUMBER(1) DEFAULT 0,
    ESCUELA_DETALLE VARCHAR2(250),
    GRADO_ESCUELA VARCHAR2(100),
    TIENE_DNI NUMBER(1) DEFAULT 0,
    TIENE_SIS NUMBER(1) DEFAULT 0,
    FAMILIARES_VIVE VARCHAR2(2000),
    HORARIOS_DIAS VARCHAR2(1000),
    
    -- Principales Indicadores de Riesgo
    RIESGO_SALUD VARCHAR2(2000),
    RIESGO_VIOLENCIA VARCHAR2(2000),
    RIESGO_ESCOLAR VARCHAR2(2000),
    RIESGO_LABORAL_PADRES VARCHAR2(2000),
    RIESGO_FAMILIAR VARCHAR2(2000),
    
    -- Acciones y Acuerdos
    ACCIONES_REALIZADAS VARCHAR2(2000),
    OTRA_SITUACION VARCHAR2(2000),
    ACUERDOS VARCHAR2(2000),
    
    -- Control/Auditoría
    EDUCADOR_ID NUMBER NOT NULL,
    SEDE_ID NUMBER NOT NULL,
    NNA_ID NUMBER NULL, -- Relación cuando se promueve a F03
    ESTADO VARCHAR2(50) DEFAULT 'PENDIENTE' NOT NULL, -- PENDIENTE, NO_LOCALIZADO, PROMOVIDO_F03, DERIVADO_EXTERNO
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_URG_SEDE ON NNA_URGENCIA_F15(SEDE_ID);
CREATE INDEX IDX_URG_EDUCADOR ON NNA_URGENCIA_F15(EDUCADOR_ID);
CREATE INDEX IDX_URG_NNA ON NNA_URGENCIA_F15(NNA_ID);
