-- ============================================================
-- Migración 013: tracking de fases del servicio
--
-- PROBLEMA QUE RESUELVE
--
-- La "fase" del NNA estaba representada en cinco lugares que no se hablaban:
--
--   1. NNA_CASO.ESTADO         → traducido a etiquetas de fase por los tableros
--   2. NNA_CASO.FASE           → columna existente, escrita 'CONTACTO_INICIAL'
--                                 hardcodeada al crear el caso y JAMÁS actualizada
--   3. PROCESO_LOGROS.Fn_FIN   → las fechas del F05
--   4. EXP_FOLIO 'F05-FASE-N'  → de ahí infería el frontend si una fase cerró
--   5. "¿tiene PTI activo?"    → la bandeja del coordinador
--
-- Consecuencias reales: la Fase II valía 0 en todas las sedes porque nadie
-- ponía ESTADO='INTERVENCION'; el Resumen del Caso imprimía "Fase
-- CONTACTO_INICIAL" bajo el título FASE ACTUAL; y cerrar el F13 no cerraba
-- el caso, así que los egresados seguían contando como activos.
--
-- A partir de esta migración hay UNA fuente: NNA_CASO.FASE dice dónde está,
-- CASO_FASE dice cómo llegó ahí.
--
--
-- POR QUÉ UNA TABLA Y NO SOLO LA COLUMNA
--
-- La columna responde "¿en qué fase está?". La tabla responde "¿cuánto duró
-- su Fase I?, ¿necesitó extensión?, ¿quién la cerró?, ¿está vencida?".
-- Eso es el tracking, y una columna sola no lo da.
--
--
-- PLAZOS (RDE 069-2021, GUIA_OPERATIVA_SEC.md)
--
--   FASE I   — Contacto e Integración .................  3 meses (+1 extensión)
--   FASE II  — Desarrollo e Intervención para la
--              Restitución de Derechos ................ 15 meses (+1 extensión)
--   FASE III — Seguimiento y Egreso ...................  6 meses
--                                                       ─────────
--                                              total    24 meses
--
--
-- QUÉ NO HACE ESTA MIGRACIÓN
--
-- No promueve a nadie de fase automáticamente. El vencimiento del plazo
-- genera una alerta, no un ascenso. La guía es explícita: si al mes de
-- extensión no se lograron los ítems, el NNA NO pasa a Fase II. Y los
-- educadores lo confirmaron en la reunión del 05/08/2026 (Luis Gutiérrez):
--
--   "No necesariamente todo tiene que cumplirse para pasar. Porque hay chicos
--    que en la segunda fase los ponemos a estudiar, le matriculamos, pero por
--    su falta de interés ya no van. Entonces, si se tiene que cumplir todos,
--    entonces nunca pasaremos de fase."
--
-- El criterio es humano en ambos sentidos. Lo automático es el cálculo, el
-- cronómetro y el registro — no la decisión.
--
--
-- Idempotente: se puede ejecutar más de una vez sin romper nada.
-- Ejecutar como SEC_USER, o con el prefijo si estás conectado como SYSTEM.
-- Sin comandos SQL*Plus: sirve igual en DBeaver.
-- ============================================================


-- ── 1. Tabla de tracking ────────────────────────────────────────────────────
-- Una fila por fase por caso. La fase vigente es la que tiene FECHA_FIN NULL.
DECLARE
    v_existe NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_existe
      FROM ALL_TABLES
     WHERE OWNER = 'SEC_USER' AND TABLE_NAME = 'CASO_FASE';

    IF v_existe = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SEC_USER.CASO_FASE (
                ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                CASO_ID         NUMBER        NOT NULL,
                FASE            VARCHAR2(3)   NOT NULL,
                FECHA_INICIO    DATE          NOT NULL,
                FECHA_FIN       DATE,
                PLAZO_MESES     NUMBER(2)     NOT NULL,
                MESES_EXTENSION NUMBER(2)     DEFAULT 0 NOT NULL,
                ESTADO          VARCHAR2(15)  DEFAULT 'EN_CURSO' NOT NULL,
                CERRADA_POR_ID  NUMBER,
                OBSERVACION     VARCHAR2(500),
                CREATED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT CK_CASO_FASE_FASE
                    CHECK (FASE IN ('I','II','III')),
                CONSTRAINT CK_CASO_FASE_ESTADO
                    CHECK (ESTADO IN ('EN_CURSO','CERRADA','EXTENDIDA','NO_SUPERADA')),
                CONSTRAINT FK_CASO_FASE_CASO
                    FOREIGN KEY (CASO_ID) REFERENCES SEC_USER.NNA_CASO(ID)
            )
        ]';
    END IF;
END;
/

COMMENT ON TABLE SEC_USER.CASO_FASE IS
    'Tracking de fases del servicio. Una fila por fase transitada. La fase vigente es la que tiene FECHA_FIN NULL';
COMMENT ON COLUMN SEC_USER.CASO_FASE.PLAZO_MESES IS
    'Plazo normativo de la fase segun RDE 069-2021: I=3, II=15, III=6';
COMMENT ON COLUMN SEC_USER.CASO_FASE.MESES_EXTENSION IS
    'Meses de extension otorgados con Informe Tecnico. Fases I y II admiten 1';
COMMENT ON COLUMN SEC_USER.CASO_FASE.ESTADO IS
    'EN_CURSO / CERRADA (paso a la siguiente) / EXTENDIDA / NO_SUPERADA (no paso)';


-- Un caso no puede transitar dos veces la misma fase.
DECLARE
    v_existe NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_existe
      FROM ALL_INDEXES
     WHERE OWNER = 'SEC_USER' AND INDEX_NAME = 'UX_CASO_FASE_CASO_FASE';
    IF v_existe = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE UNIQUE INDEX SEC_USER.UX_CASO_FASE_CASO_FASE
                 ON SEC_USER.CASO_FASE (CASO_ID, FASE)';
    END IF;
END;
/

-- Los tableros preguntan siempre por la fase vigente de un conjunto de casos.
DECLARE
    v_existe NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_existe
      FROM ALL_INDEXES
     WHERE OWNER = 'SEC_USER' AND INDEX_NAME = 'IX_CASO_FASE_VIGENTE';
    IF v_existe = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX SEC_USER.IX_CASO_FASE_VIGENTE
                 ON SEC_USER.CASO_FASE (CASO_ID, FECHA_FIN)';
    END IF;
END;
/


-- ── 2. Normalizar NNA_CASO.FASE ─────────────────────────────────────────────
-- La columna ya existe y es NOT NULL, pero guarda 'CONTACTO_INICIAL' en todas
-- las filas porque el INSERT la escribe hardcodeada. Se amplía a VARCHAR2(10)
-- para que quepa 'EGRESADO' y se normaliza el vocabulario a I / II / III.
DECLARE
    v_len NUMBER;
BEGIN
    SELECT DATA_LENGTH INTO v_len
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'SEC_USER' AND TABLE_NAME = 'NNA_CASO' AND COLUMN_NAME = 'FASE';
    IF v_len < 10 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SEC_USER.NNA_CASO MODIFY (FASE VARCHAR2(10))';
    END IF;
END;
/

-- Quitar el CHECK viejo de la columna FASE.
--
-- La base tiene una restricción SEC_USER.CHK_FASE que solo admite el
-- vocabulario antiguo ('CONTACTO_INICIAL' y compañía). No está en ninguna
-- migración del repositorio —se creó fuera del código versionado—, así que el
-- UPDATE de abajo choca contra ella con ORA-02290.
--
-- Se busca por CONSTRAINT_TYPE = 'C' sobre la tabla, comprobando que la
-- condición mencione FASE. Así se elimina llame como se llame, sin depender de
-- que el nombre sea exactamente CHK_FASE.
--
-- SEARCH_CONDITION_VC (12.1.0.2+) es VARCHAR2: SEARCH_CONDITION es LONG y no
-- se puede filtrar con LIKE.
DECLARE
    v_nombre VARCHAR2(128);
BEGIN
    FOR c IN (
        SELECT CONSTRAINT_NAME
          FROM ALL_CONSTRAINTS
         WHERE OWNER = 'SEC_USER'
           AND TABLE_NAME = 'NNA_CASO'
           AND CONSTRAINT_TYPE = 'C'
           AND UPPER(SEARCH_CONDITION_VC) LIKE '%FASE%'
           AND UPPER(SEARCH_CONDITION_VC) NOT LIKE '%NOT NULL%'
    ) LOOP
        v_nombre := c.CONSTRAINT_NAME;
        EXECUTE IMMEDIATE
            'ALTER TABLE SEC_USER.NNA_CASO DROP CONSTRAINT ' || v_nombre;
        DBMS_OUTPUT.PUT_LINE('Restriccion eliminada: ' || v_nombre);
    END LOOP;
END;
/

-- Cualquier valor del vocabulario viejo pasa a 'I'. 'CONTACTO_INICIAL' es
-- literalmente la Fase I, así que la traducción es exacta, no una suposición.
UPDATE SEC_USER.NNA_CASO
   SET FASE = 'I'
 WHERE FASE NOT IN ('I','II','III','EGRESADO') OR FASE IS NULL;

COMMIT;


-- ── 3. Backfill desde el F05 ────────────────────────────────────────────────
-- La fase real de cada caso es la que su educador cerró en la Ficha de Proceso
-- de Logros. Se promueve una fase por cada Fn_FIN sellado.
--
-- Nota: cerrar la Fase III no significa egresado — el egreso lo declara el F13.
-- Un NNA puede tener la Fase III cerrada y seguir en el servicio hasta que se
-- finalice su Ficha de Egreso.
UPDATE SEC_USER.NNA_CASO c
   SET FASE = (
        SELECT CASE
                   WHEN MAX(p.F3_FIN) IS NOT NULL THEN 'III'
                   WHEN MAX(p.F2_FIN) IS NOT NULL THEN 'III'
                   WHEN MAX(p.F1_FIN) IS NOT NULL THEN 'II'
                   ELSE 'I'
               END
          FROM SEC_USER.PROCESO_LOGROS p
         WHERE p.CASO_ID = c.ID
   )
 WHERE EXISTS (SELECT 1 FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID)
   AND c.FASE <> 'EGRESADO';


-- Los casos con Informe de Cierre finalizado quedan como EGRESADO. Este UPDATE
-- arregla de raíz el bug de CerrarCasoUseCase, que creaba el informe y el folio
-- pero nunca cerraba el caso: hoy todos los egresados siguen contando como
-- activos en los cuatro tableros y en la carga de cada educador.
UPDATE SEC_USER.NNA_CASO c
   SET FASE   = 'EGRESADO',
       ESTADO = 'CERRADO',
       FECHA_CIERRE = NVL(
           FECHA_CIERRE,
           (SELECT MAX(i.FECHA_EGRESO)
              FROM SEC_USER.EXP_INFORME_CIERRE i
             WHERE i.CASO_ID = c.ID)
       )
 WHERE EXISTS (
        SELECT 1 FROM SEC_USER.EXP_INFORME_CIERRE i
         WHERE i.CASO_ID = c.ID
           AND i.ESTADO IN ('FINALIZADO','PEND_COORDINADOR','FIRMADO')
   );

COMMIT;


-- Recién ahora se pone el CHECK con el vocabulario nuevo: si se creara antes
-- del backfill, rechazaría las filas que todavía tienen el valor viejo.
DECLARE
    v_existe NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_existe
      FROM ALL_CONSTRAINTS
     WHERE OWNER = 'SEC_USER' AND CONSTRAINT_NAME = 'CK_NNA_CASO_FASE';
    IF v_existe = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE SEC_USER.NNA_CASO ADD CONSTRAINT CK_NNA_CASO_FASE
                 CHECK (FASE IN (''I'',''II'',''III'',''EGRESADO''))';
    END IF;
END;
/


-- ── 4. Reconstruir el historial de fases ────────────────────────────────────
-- Se arma CASO_FASE a partir de las fechas que ya tiene el F05. Donde no hay
-- fecha se usa la de apertura del caso: es una aproximación, pero es la mejor
-- disponible y queda marcada en OBSERVACION para no confundirla con un dato
-- registrado por el educador.

-- Fase I — todos los casos la transitaron.
INSERT INTO SEC_USER.CASO_FASE
    (CASO_ID, FASE, FECHA_INICIO, FECHA_FIN, PLAZO_MESES, ESTADO, OBSERVACION)
SELECT c.ID,
       'I',
       NVL(
           (SELECT MAX(NVL(p.F1_INICIO, p.FECHA_INGRESO))
              FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID),
           CAST(c.FECHA_APERTURA AS DATE)
       ),
       (SELECT MAX(p.F1_FIN) FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID),
       3,
       CASE
           WHEN (SELECT MAX(p.F1_FIN) FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID)
                IS NOT NULL THEN 'CERRADA'
           ELSE 'EN_CURSO'
       END,
       'Reconstruida por la migracion 013 a partir del F05'
  FROM SEC_USER.NNA_CASO c
 WHERE NOT EXISTS (
        SELECT 1 FROM SEC_USER.CASO_FASE f WHERE f.CASO_ID = c.ID AND f.FASE = 'I'
   );

-- Fase II — solo los casos que cerraron la Fase I.
INSERT INTO SEC_USER.CASO_FASE
    (CASO_ID, FASE, FECHA_INICIO, FECHA_FIN, PLAZO_MESES, ESTADO, OBSERVACION)
SELECT c.ID,
       'II',
       (SELECT MAX(NVL(p.F2_INICIO, p.F1_FIN + 1))
          FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID),
       (SELECT MAX(p.F2_FIN) FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID),
       15,
       CASE
           WHEN (SELECT MAX(p.F2_FIN) FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID)
                IS NOT NULL THEN 'CERRADA'
           ELSE 'EN_CURSO'
       END,
       'Reconstruida por la migracion 013 a partir del F05'
  FROM SEC_USER.NNA_CASO c
 WHERE EXISTS (
        SELECT 1 FROM SEC_USER.PROCESO_LOGROS p
         WHERE p.CASO_ID = c.ID AND p.F1_FIN IS NOT NULL
   )
   AND NOT EXISTS (
        SELECT 1 FROM SEC_USER.CASO_FASE f WHERE f.CASO_ID = c.ID AND f.FASE = 'II'
   );

-- Fase III — solo los casos que cerraron la Fase II.
INSERT INTO SEC_USER.CASO_FASE
    (CASO_ID, FASE, FECHA_INICIO, FECHA_FIN, PLAZO_MESES, ESTADO, OBSERVACION)
SELECT c.ID,
       'III',
       (SELECT MAX(NVL(p.F3_INICIO, p.F2_FIN + 1))
          FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID),
       (SELECT MAX(p.F3_FIN) FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID),
       6,
       CASE
           WHEN (SELECT MAX(p.F3_FIN) FROM SEC_USER.PROCESO_LOGROS p WHERE p.CASO_ID = c.ID)
                IS NOT NULL THEN 'CERRADA'
           ELSE 'EN_CURSO'
       END,
       'Reconstruida por la migracion 013 a partir del F05'
  FROM SEC_USER.NNA_CASO c
 WHERE EXISTS (
        SELECT 1 FROM SEC_USER.PROCESO_LOGROS p
         WHERE p.CASO_ID = c.ID AND p.F2_FIN IS NOT NULL
   )
   AND NOT EXISTS (
        SELECT 1 FROM SEC_USER.CASO_FASE f WHERE f.CASO_ID = c.ID AND f.FASE = 'III'
   );

COMMIT;


-- ── 5. Cerrar las fases de los casos ya egresados ───────────────────────────
-- Un caso egresado no puede tener una fase en curso. Se cierra con la fecha
-- de egreso de su informe.
-- El SYSDATE final importa: si el informe no tiene fecha de egreso, o el caso
-- quedó marcado como egresado sin informe, sin él la fila se quedaría con
-- FECHA_FIN nula — o sea, contada como fase vigente y vencida, en un caso
-- que ya terminó.
UPDATE SEC_USER.CASO_FASE f
   SET FECHA_FIN = NVL(
           FECHA_FIN,
           NVL(
               (SELECT CAST(MAX(i.FECHA_EGRESO) AS DATE)
                  FROM SEC_USER.EXP_INFORME_CIERRE i
                 WHERE i.CASO_ID = f.CASO_ID),
               SYSDATE
           )
       ),
       ESTADO = 'CERRADA'
 WHERE f.FECHA_FIN IS NULL
   AND EXISTS (
        SELECT 1 FROM SEC_USER.NNA_CASO c
         WHERE c.ID = f.CASO_ID AND c.FASE = 'EGRESADO'
   );

COMMIT;


-- ============================================================
-- VERIFICACIÓN
-- ============================================================

-- 0. Restricciones sobre FASE: debe quedar solo CK_NNA_CASO_FASE con el
--    vocabulario nuevo. Si aparece CHK_FASE, el paso 2 no se ejecutó.
SELECT CONSTRAINT_NAME, SEARCH_CONDITION_VC
  FROM ALL_CONSTRAINTS
 WHERE OWNER = 'SEC_USER'
   AND TABLE_NAME = 'NNA_CASO'
   AND CONSTRAINT_TYPE = 'C'
   AND UPPER(SEARCH_CONDITION_VC) LIKE '%FASE%';

-- 1. Distribución de fases tras el backfill
SELECT FASE, COUNT(*) AS CANTIDAD
  FROM SEC_USER.NNA_CASO
 GROUP BY FASE
 ORDER BY FASE;

-- 2. Historial reconstruido
SELECT FASE, ESTADO, COUNT(*) AS CANTIDAD
  FROM SEC_USER.CASO_FASE
 GROUP BY FASE, ESTADO
 ORDER BY FASE, ESTADO;

-- 3. Coherencia: la fase vigente de CASO_FASE debe coincidir con NNA_CASO.FASE.
--    Esta consulta debe devolver CERO filas.
SELECT c.ID, c.CODIGO_CASO, c.FASE AS FASE_CASO, f.FASE AS FASE_VIGENTE
  FROM SEC_USER.NNA_CASO c
  JOIN SEC_USER.CASO_FASE f ON f.CASO_ID = c.ID AND f.FECHA_FIN IS NULL
 WHERE c.FASE <> f.FASE
   AND c.FASE <> 'EGRESADO';

-- 4. Fases vencidas hoy — el semáforo que alimentará las alertas
SELECT f.FASE,
       COUNT(*) AS VENCIDAS,
       ROUND(AVG(MONTHS_BETWEEN(SYSDATE, f.FECHA_INICIO)), 1) AS MESES_PROMEDIO
  FROM SEC_USER.CASO_FASE f
  JOIN SEC_USER.NNA_CASO c ON c.ID = f.CASO_ID
 WHERE f.FECHA_FIN IS NULL
   AND c.ESTADO <> 'CERRADO'
   AND ADD_MONTHS(f.FECHA_INICIO, f.PLAZO_MESES + f.MESES_EXTENSION) < SYSDATE
 GROUP BY f.FASE
 ORDER BY f.FASE;
