-- Script DDL para la tabla DERIVACION
CREATE TABLE DERIVACION (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CASO_ID NUMBER NOT NULL,
    SEDE_ID NUMBER NOT NULL,
    TIPO VARCHAR2(20) NOT NULL CHECK (TIPO IN ('INTERNA', 'EXTERNA')),
    ENTIDAD_EXTERNA VARCHAR2(100),
    REMITENTE_ID NUMBER NOT NULL,
    DESTINATARIO_ID NUMBER,
    MOTIVO VARCHAR2(500) NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (ESTADO IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA')),
    FECHA_DERIVACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_RESPUESTA TIMESTAMP,
    OBSERVACIONES VARCHAR2(500)
);

-- Índices útiles para las búsquedas comunes
CREATE INDEX IDX_DERIVACION_CASO ON DERIVACION(CASO_ID);
CREATE INDEX IDX_DERIVACION_DESTINATARIO ON DERIVACION(DESTINATARIO_ID);
CREATE INDEX IDX_DERIVACION_SEDE ON DERIVACION(SEDE_ID);
