-- ============================================================
-- MIGRACIÓN 001 — expediente-service: EXP_FOLIO, EXP_INFORME_CIERRE
-- Motor: Oracle 12c+
-- ============================================================

-- ── EXP_FOLIO ────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE '
  CREATE TABLE EXP_FOLIO (
    ID              NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CASO_ID         NUMBER        NOT NULL,
    SEDE_ID         NUMBER        NOT NULL,
    NUMERO_FOLIO    NUMBER        NOT NULL,
    TIPO_DOCUMENTO  VARCHAR2(30)  NOT NULL,
    TITULO          VARCHAR2(300) NOT NULL,
    ARCHIVO_URL     VARCHAR2(500) NOT NULL,
    HASH_DOCUMENTO  VARCHAR2(64),
    CREADO_POR_ID   NUMBER        NOT NULL,
    FECHA_CREACION  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_FOLIO_CASO_NUM UNIQUE (CASO_ID, NUMERO_FOLIO)
  )
'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- ── EXP_INFORME_CIERRE ────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE '
  CREATE TABLE EXP_INFORME_CIERRE (
    ID                  NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CODIGO_INFORME      VARCHAR2(30),
    CASO_ID             NUMBER        NOT NULL,
    MOTIVO_EGRESO       VARCHAR2(100) NOT NULL,
    FECHA_EGRESO        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    SITUACION_FAMILIAR  VARCHAR2(100),
    SITUACION_EDUCATIVA VARCHAR2(100),
    LOGROS_ALCANZADOS   VARCHAR2(2000),
    RECOMENDACIONES     VARCHAR2(2000),
    ARCHIVO_URL         VARCHAR2(500),
    CREADO_POR_ID       NUMBER        NOT NULL,
    CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_INFORME_CASO UNIQUE (CASO_ID)
  )
'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- ── Índices ───────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_FOLIO_CASO  ON EXP_FOLIO(CASO_ID)';  EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_FOLIO_SEDE  ON EXP_FOLIO(SEDE_ID)';  EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_FOLIO_TIPO  ON EXP_FOLIO(TIPO_DOCUMENTO)'; EXCEPTION WHEN OTHERS THEN NULL; END;/
