-- ============================================================
-- MIGRACIÓN 002 — expediente-service: EXP_INFORME_SITUACIONAL
-- Motor: Oracle 12c+
-- ============================================================

BEGIN EXECUTE IMMEDIATE '
  CREATE TABLE EXP_INFORME_SITUACIONAL (
    ID                  NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CASO_ID             NUMBER        NOT NULL,
    FECHA_INFORME       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DESTINATARIO        VARCHAR2(300) NOT NULL,
    ASUNTO              VARCHAR2(300) NOT NULL,
    ANTECEDENTES        CLOB,
    ESTRATEGIAS         CLOB,
    SITUACION_SALUD     CLOB,
    SITUACION_EDUCATIVA CLOB,
    SITUACION_FAMILIAR  CLOB,
    CONCLUSIONES        CLOB,
    RECOMENDACIONES     CLOB,
    CREADO_POR_ID       NUMBER        NOT NULL,
    CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_INF_SIT_CASO UNIQUE (CASO_ID)
  )
'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_INF_SIT_CASO ON EXP_INFORME_SITUACIONAL(CASO_ID)'; EXCEPTION WHEN OTHERS THEN NULL; END;/
