-- ============================================================
-- MIGRACIÓN 001 — nna-service: Tablas NNA, CARPETA, CASO
-- Motor: Oracle 12c+
-- ============================================================

-- ── NNA_CARPETA ──────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE '
  CREATE TABLE NNA_CARPETA (
    ID          NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CODIGO      VARCHAR2(100) NOT NULL,
    ANIO        NUMBER(4)     NOT NULL,
    CORRELATIVO NUMBER        NOT NULL,
    SEDE_ID     NUMBER,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_CARPETA_CODIGO UNIQUE (CODIGO),
    CONSTRAINT FK_CARPETA_SEDE FOREIGN KEY (SEDE_ID) REFERENCES SEC_SEDE(ID)
  )
'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- ── NNA ──────────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE '
  CREATE TABLE NNA (
    ID                         NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CODIGO_FICHA03             VARCHAR2(30),
    NOMBRES                    VARCHAR2(150) NOT NULL,
    APELLIDO_PATERNO           VARCHAR2(100) NOT NULL,
    APELLIDO_MATERNO           VARCHAR2(100),
    TIPO_DOC                   VARCHAR2(20)  DEFAULT ''DNI'' NOT NULL,
    NUMERO_DOC                 VARCHAR2(20),
    FECHA_NACIMIENTO           TIMESTAMP,
    TIENE_PARTIDA_NACIMIENTO   NUMBER(1)     DEFAULT 0,
    DETALLE_SIN_DOC            VARCHAR2(300),
    DEPARTAMENTO_NAC           VARCHAR2(60),
    PROVINCIA_NAC              VARCHAR2(60),
    DISTRITO_NAC               VARCHAR2(60),
    SEXO                       VARCHAR2(1),
    NACIONALIDAD               VARCHAR2(30)  DEFAULT ''PERUANA'',
    CARPETA_ID                 NUMBER,
    DOMICILIO_ACTUAL           VARCHAR2(300),
    REFERENCIA_DOMICILIO       VARCHAR2(300),
    DEPARTAMENTO_DOM           VARCHAR2(60),
    PROVINCIA_DOM              VARCHAR2(60),
    DISTRITO_DOM               VARCHAR2(60),
    TELEFONO_CONTACTO          VARCHAR2(20),
    NOMBRE_TUTOR               VARCHAR2(150),
    VIVE_CON                   VARCHAR2(30),
    DETALLE_VIVE_CON           VARCHAR2(200),
    TIENE_HERMANOS             NUMBER(1)     DEFAULT 0,
    CANT_HERMANOS              NUMBER        DEFAULT 0,
    DETALLES_HERMANOS          VARCHAR2(500),
    LUGAR_PERNOCTE             VARCHAR2(30),
    DETALLE_LUGAR_PERNOCTE     VARCHAR2(200),
    TIENE_ANTECEDENTE_ALBERGUE NUMBER(1)     DEFAULT 0,
    DETALLE_ANTECEDENTE_ALBERGUE VARCHAR2(300),
    AFILIADO_SIS               VARCHAR2(10),
    AFILIADO_OTRO_SEGURO       VARCHAR2(10),
    DETALLE_OTRO_SEGURO        VARCHAR2(100),
    SUFRE_ENFERMEDAD           NUMBER(1)     DEFAULT 0,
    DETALLE_ENFERMEDAD         VARCHAR2(300),
    OBSERVACIONES_SALUD        VARCHAR2(500),
    TIENE_DISCAPACIDAD         NUMBER(1)     DEFAULT 0,
    TIPO_DISCAPACIDAD          VARCHAR2(30),
    DETALLE_DISCAPACIDAD       VARCHAR2(300),
    ESTUDIA_ACTUALMENTE        NUMBER(1)     DEFAULT 0,
    NIVEL_EDUCATIVO            VARCHAR2(30),
    GRADO_ESTUDIO              VARCHAR2(20),
    INSTITUCION_EDUCATIVA      VARCHAR2(200),
    MODALIDAD_ESTUDIO          VARCHAR2(20),
    DETALLE_NO_ESTUDIA         VARCHAR2(300),
    ACTIVIDADES_TIEMPO_LIBRE   VARCHAR2(500),
    FOTO_URL                   VARCHAR2(500),
    CARACTERISTICAS            VARCHAR2(1000),
    CREATED_AT                 TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT                 TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_NNA_NUMERO_DOC   UNIQUE (NUMERO_DOC),
    CONSTRAINT UQ_NNA_CODIGO_F03   UNIQUE (CODIGO_FICHA03),
    CONSTRAINT FK_NNA_CARPETA      FOREIGN KEY (CARPETA_ID) REFERENCES NNA_CARPETA(ID)
  )
'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- ── NNA_CASO ─────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE '
  CREATE TABLE NNA_CASO (
    ID                    NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CODIGO_CASO           VARCHAR2(30)  NOT NULL,
    NNA_ID                NUMBER        NOT NULL,
    SEDE_ID               NUMBER        NOT NULL,
    RESPONSABLE_ID        NUMBER        NOT NULL,
    DISTRITO_INTERVENCION VARCHAR2(100),
    ZONA_INTERVENCION     VARCHAR2(100),
    PERFIL                VARCHAR2(30)  NOT NULL,
    ACTIVIDAD_REALIZADA   VARCHAR2(300),
    TIEMPO_EN_CALLE       VARCHAR2(100),
    HORARIO_INICIO        VARCHAR2(10),
    HORARIO_FIN           VARCHAR2(10),
    HORARIO_INICIO2       VARCHAR2(10),
    HORARIO_FIN2          VARCHAR2(10),
    DIAS_TRABAJO          VARCHAR2(50),
    CONDICION             VARCHAR2(30),
    ANTECEDENTE_INSTITUCIONAL VARCHAR2(300),
    FECHA_ABORDAJE        TIMESTAMP,
    FECHA_INGRESO         TIMESTAMP,
    FECHA_REINGRESO       TIMESTAMP,
    FECHA_CAMBIO_PERFIL   TIMESTAMP,
    ESTADO                VARCHAR2(30)  DEFAULT ''EN_EVALUACION'' NOT NULL,
    NIVEL_RIESGO          VARCHAR2(10),
    SITUACION_CALLE       VARCHAR2(30),
    FECHA_APERTURA        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_CIERRE          TIMESTAMP,
    UPDATED_AT            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_CASO_CODIGO UNIQUE (CODIGO_CASO),
    CONSTRAINT FK_CASO_NNA    FOREIGN KEY (NNA_ID) REFERENCES NNA(ID)
  )
'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- ── NNA_HISTORIAL_ESTADO ──────────────────────────────────────
BEGIN EXECUTE IMMEDIATE '
  CREATE TABLE NNA_HISTORIAL_ESTADO (
    ID              NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CASO_ID         NUMBER        NOT NULL,
    ESTADO_ANTERIOR VARCHAR2(30),
    ESTADO_NUEVO    VARCHAR2(30)  NOT NULL,
    USUARIO_ID      NUMBER        NOT NULL,
    FECHA_CAMBIO    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    MOTIVO          VARCHAR2(500),
    TIPO_CAMBIO     VARCHAR2(30)  DEFAULT ''CAMBIO_ESTADO'',
    CONSTRAINT FK_HIST_CASO FOREIGN KEY (CASO_ID) REFERENCES NNA_CASO(ID)
  )
'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- ── NNA_TRASLADO ──────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE '
  CREATE TABLE NNA_TRASLADO (
    ID                    NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    CASO_ID               NUMBER        NOT NULL,
    NNA_ID                NUMBER        NOT NULL,
    TIPO                  VARCHAR2(20)  NOT NULL,
    SEDE_ORIGEN_ID        NUMBER        NOT NULL,
    SEDE_DESTINO_ID       NUMBER        NOT NULL,
    COORDINADOR_ORIGEN_ID NUMBER        NOT NULL,
    COORDINADOR_DEST_ID   NUMBER,
    MOTIVO                VARCHAR2(500) NOT NULL,
    ESTADO                VARCHAR2(20)  DEFAULT ''PENDIENTE'' NOT NULL,
    FECHA_SOLICITUD       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_RESPUESTA       TIMESTAMP,
    OBSERVACIONES         VARCHAR2(500),
    CONSTRAINT FK_TRASLADO_CASO FOREIGN KEY (CASO_ID) REFERENCES NNA_CASO(ID),
    CONSTRAINT FK_TRASLADO_NNA  FOREIGN KEY (NNA_ID)  REFERENCES NNA(ID)
  )
'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- ── Índices ───────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CASO_NNA       ON NNA_CASO(NNA_ID)';         EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CASO_SEDE      ON NNA_CASO(SEDE_ID)';        EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CASO_RESP      ON NNA_CASO(RESPONSABLE_ID)'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CASO_ESTADO    ON NNA_CASO(ESTADO)';         EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_HIST_CASO      ON NNA_HISTORIAL_ESTADO(CASO_ID)'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_TRASLADO_CASO  ON NNA_TRASLADO(CASO_ID)';    EXCEPTION WHEN OTHERS THEN NULL; END;/
